{{- if .Values.ingress.enabled }}
# Source: https://www.reddit.com/r/Traefik/comments/d36iry/traefik_20_with_certmanager/
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: {{ .Release.Name }}-letsencrypt-prod
    kubernetes.io/ingress.class: fake
  labels:
    traefik2: "true"
  name: {{ .Release.Name }}-argocd-ingress
  namespace: argocd
spec:
  rules:
  - host: {{ .Values.ingress.argocd.host }}
    http:
      paths:
      - backend:
          serviceName: argocd-server
          servicePort: 80
        path: /
  tls:
  - hosts:
    - {{ .Values.ingress.argocd.host }}
    secretName: {{ .Release.Name }}-argocd-tls
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: {{ .Release.Name }}-argocd-https-only
  namespace: argocd
spec:
  redirectScheme:
    scheme: https
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Release.Name }}-argocd-80
  namespace: argocd
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`{{ .Values.ingress.argocd.host }}`) && PathPrefix(`/`)
      kind: Rule
      middlewares:
        - name: {{ .Release.Name }}-argocd-https-only
      services:
        - name: argocd-server
          port: 80
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Release.Name }}-argocd-tls
  namespace: argocd
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`{{ .Values.ingress.argocd.host }}`) && PathPrefix(`/`)
      kind: Rule
      services:
        - name: argocd-server
          port: 80
  tls:
    secretName: {{ .Release.Name }}-argocd-tls
{{- end }}