kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Release.Name }}-controller
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name }}-controller
roleRef:
  kind: Role
  name: {{ .Release.Name }}-controller
  apiGroup: rbac.authorization.k8s.io
